server:
  port: 9097
  
spring:
  application.name: resilience4j-demo

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true
      
      
resilience4j:
  retry:
    instances:
      gill:
        max-attempts: 5
        wait-duration: 5s
      
  ratelimiter:
    instances:
      suyadpreet:
        limit-for-period: 2
        limit-refresh-period: 10s
        timeout-duration: 5s
        register-health-indicator: true
        event-consumer-buffer-size: 100
